networks:
  media-centre-network:
    external: true
    name: media-centre-network

services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: Plex
    restart: unless-stopped
    network_mode: host
    environment:
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=latest
      - HOST_OS=Unraid
      - CHANGE_CONFIG_DIR_OWNERSHIP=true
    volumes:
      - /mnt/user/appdata/Plex:/config:rw
      - /mnt/user/data/media:/data:rw
      - /mnt/user/appdata/plex_transcode:/transcode:rw
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail http://127.0.0.1:32400/identity
      interval: 1m00s
      timeout: 15s
      retries: 3
      start_period: 1m00s
