name: monitoring

networks:
  media-centre-network:
    external: true
    name: media-centre-network

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /mnt/cache/appdata/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - media-centre-network
    environment:
      HOMEPAGE_ALLOWED_HOSTS: 192.168.1.234:3000,100.109.91.64:3000,localhost:3000

  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - /mnt/cache/appdata/tautulli:/config
    environment:
      - PUID={PUID}
      - PGID={PGID}
      - TZ={TZ}
    ports:
      - 8181:8181
    networks:
      - media-centre-network

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: UptimeKuma
    restart: unless-stopped
    ports:
      - '3001:3001'
    volumes:
      - '/mnt/cache/appdata/uptimekuma:/app/data'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    environment:
      - TZ=America/New_York
      - UPTIME_KUMA_IS_CONTAINER=1
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '1'
    networks:
      - media-centre-network
    healthcheck:
      test: ['CMD-SHELL', 'extra/healthcheck']
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 180s

  glances:
    image: nicolargo/glances:latest
    container_name: Glances
    restart: unless-stopped
    pid: host
    network_mode: bridge
    ports:
      - '61208:61208'
    environment:
      - GLANCES_OPT=${GLANCES_OPT}
      - PYTHON_VERSION=${PYTHON_VERSION}
      - TZ=${TZ}
      - HOST_OS=Unraid
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /etc/os-release:/etc/os-release:ro
      - /mnt/cache/appdata/glances:/etc/glances:rw
    security_opt:
      - label:disable
