networks:
  media-centre-network:
    external: true
    name: media-centre-network

services:
  # --- MAINTENANCE ---
  cleanuparr:
    image: ghcr.io/cleanuparr/cleanuparr:latest
    container_name: Cleanuparr
    networks:
      - media-centre-network
    ports:
      - '11011:11011'
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PORT=11011
      - HTTP_PORTS=11011
    volumes:
      - ${APPDATA_PATH}/Cleanuparr:/config
      - ${TORRENTS_PATH}:/downloads
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:11011/health']
      interval: 30s # Check every 30 seconds
      timeout: 10s # Allow up to 10 seconds for response
      start_period: 30s # Wait 30 seconds before first check
      retries: 3 # Mark unhealthy after 3 consecutive failures

  maintainerr:
    image: ghcr.io/maintainerr/maintainerr:latest
    container_name: Maintainerr
    networks:
      - media-centre-network
    ports:
      - '6246:6246'
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA_PATH}/maintainerr:/config
    restart: unless-stopped

  # IFRASTRUCTURE & DEPENDENCIES
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: CloudflaredTunnel
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=${TZ}
    entrypoint: ['cloudflared', '--no-autoupdate']
    command: ['tunnel', 'run', '--token', '${CLOUDFLARE_TUNNEL_TOKEN}']

  flaresolverr:
    image: binhex/arch-flaresolverr:latest
    container_name: Flaresolverr
    networks:
      - media-centre-network
    ports:
      - '8191:8191'
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    volumes:
      - ${APPDATA_PATH}/binhex-flaresolverr:/config
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8191/']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # --- INDEXING ---

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: Prowlarr
    networks:
      - media-centre-network
    ports:
      - '9697:9696'
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA_PATH}/prowlarr:/config
    restart: unless-stopped
    depends_on:
      flaresolverr:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9696/']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
