services:
  plexcache-d:
    image: ghcr.io/studionirin/plexcache-d:latest
    container_name: plexcache-d
    restart: unless-stopped
    network_mode: bridge
    ports:
      - '5757:5757'
    volumes:
      - /mnt/user/appdata/plexcache:/config
      - /mnt/cache:/mnt/cache
      - /mnt/user0:/mnt/user0
      - /mnt/user:/mnt/user
    environment:
      - PUID=99
      - PGID=100
      - TZ=America/New_York
